# .bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# User specific aliases and functions

## Aliases
alias ls='ls --color=auto'
alias wowls='instawow list'
alias update='yay -Syy'
alias wowupdate='instawow update'
alias upgrade='yay -Syu; instawow update'
alias wowupgrade='instawow update'
alias install='yay -S'
alias wowinstall='instawow install'
alias remove='yay -Rns'
alias wowremove='instawow remove'
alias search='yay'
alias wowsearch='instawow search'
alias clean='sudo paccache -rk1 && yay -Sc && yay -Rns $(pacman -Qtdq)'
alias ikey='gpg --keyserver keyserver.ubuntu.com --recv'

## Terminal prompt
PS1='\W > '

## Defaults
export EDITOR='vim'
export VISUAL='vim'
export MAKEFLAGS="-j$(nproc)"

## Colorscheme
(cat ~/.cache/wal/sequences &)
source ~/.cache/wal/colors-tty.sh

## Autorun
ufetch

## Git prompt
if [ -f /usr/lib/bash-git-prompt/gitprompt.sh ]; then
	GIT_PROMPT_ONLY_IN_REPO=1
	GIT_PROMPT_THEME=Default_Arch
	GIT_PROMPT_END_USER=" \n\W > "
	source /usr/lib/bash-git-prompt/gitprompt.sh
fi
